### ISSUE TITLE
FlaggedRevs config should be changed

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#152]
Possible shouldn't even be enabled by default, as it isn't on most wikis, but as we don't allow users to change the config yet, we should at least make the give the default user appropriate permissions (`autoreview` etc.)

**Comment by edg2s** [comment]
Is there a way to do this with group permissions in LocalSettings?

**Comment by MatmaRex** [comment]
Do what? Allow any user to review changes? I feel like that's counterproductive for testing FlaggedRevs, since you presumably need a way to test what the users who can't review see.

Also, #155 effectively disables FlaggedRevs by default (it's not in the default preset), I think we should just do that.

**Comment by edg2s** [comment]
Closing now that FR isn't included in the Wikimedia repo set
