### ISSUE TITLE
It shouldn't be possible to create a broken wiki

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#332]
Whenever the setup process fails, the wiki should be deleted, however sometimes this doesn't happen:

https://patchdemo.wmflabs.org/wikis/1d4246ea64/w/
![image](https://user-images.githubusercontent.com/180672/138748565-1cc1ac47-bdb1-4508-a94c-7e501bb01ab3.png)
(Note the missing completion time)

Our error detection should be more robust.

**Comment by kostajh** [comment]
I made a broken wiki, https://patchdemo.wmflabs.org/wikis/39c30f77c6/w

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/208893/145615621-5d46dfb3-6e1b-428f-9cc9-f47a6dfe5c6c.png">

How it happened: I created a wiki successfully (https://patchdemo.wmflabs.org/wikis/5c839eeb8d/w) then pressed back in the browser (so I was on /new.php) because I wanted to copy the login info. At that point, I started seeing what looked like new wiki creation happening, but didn't think about it and closed the tab. Then later, when looking at the index of wikis on https://patchdemo.wmflabs.org/, I saw the broken wiki had been created. I'll note that in other instances when going back to `/new.php` I see a message saying "Invalid session", so perhaps that is a clue to track this down.

**Comment by edg2s** [comment]
Reloading new.php should've created a new wiki successfully - but maybe this has something to do with closing the tab before it finished - maybe PHP decides to abort the process after a certain amount of time.

**Comment by edg2s** [comment]
Confirmed locally that closing the tab early on in new.php appears to leave a broken wiki.

**Comment by edg2s** [comment]
https://www.php.net/manual/en/features.connection-handling.php

**Comment by edg2s** [comment]
One option appears to be `ignore_user_abort( true );` which stops the script from aborting when the connection is closed. It might also be nice to abandon if the connection is closed (there appear to be some signal handlers that might work...)

**Comment by edg2s** [comment]
> then pressed back in the browser

Separately, we should guard against this triggering the installation process to restart.

**Comment by MatmaRex** [comment]
I don't really think this is a big deal, but alright.

I also don't like the fix very much… but alright.

In a perfect world, new.php should probably start some job-queue-ish thing and return immediately, and then we'd poll that from JS, instead of the way it works now as a single super-long-running request. (I wrote it that way, because I wanted to be finished with this project in about 2 days… ;) )
