### ISSUE TITLE
Transfer ownership of repo to wikimedia?

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#351]
With @MatmaRex's blessing, but this would allow for others to properly maintain the repo should BD ever be unavailable (heaven forbid).

**Comment by kostajh** [comment]
Or move to gitlab.wikimedia.org?

**Comment by MatmaRex** [comment]
I mean… does Wikimedia want to be responsible for the maintenance of this? I made it because I couldn't get anyone to make it for me. And I kind of like having it as my own project, to be honest. I'm happy to add individual people as collaborators though (for the record, @edg2s currently has access).

As for Gitlab, I'll move there instantly if you convince me that it has better support for multiple pull requests depending on each other, when the repo requires rebasing when approving pull requests (no merging). Rebasing and force-pushing from the terminal has really gotten old.

**Comment by MatmaRex** [comment]
The new GitLab repo has shared ownership.
