### ISSUE TITLE
Can't launch Patchdemo

### ISSUE THREAD

**Issue by jdlrobson** [MatmaRex/patchdemo#506]
Whenever trying to create a patchdemo I encounter the following error which occurs as it spawns:
<img width="1236" alt="Screen Shot 2022-10-24 at 10 42 01 AM" src="https://user-images.githubusercontent.com/148752/197591112-4816bd12-4492-457e-a9ce-e375227911b0.png">

```

Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Duplicate key "experimental" detected at line 1871. in /var/www/html/vendor/symfony/yaml/Parser.php:350 Stack trace: #0 /var/www/html/vendor/symfony/yaml/Parser.php(537): Symfony\Component\Yaml\Parser->doParse() #1 /var/www/html/vendor/symfony/yaml/Parser.php(208): Symfony\Component\Yaml\Parser->parseBlock() #2 /var/www/html/vendor/symfony/yaml/Parser.php(537): Symfony\Component\Yaml\Parser->doParse() #3 /var/www/html/vendor/symfony/yaml/Parser.php(332): Symfony\Component\Yaml\Parser->parseBlock() #4 /var/www/html/vendor/symfony/yaml/Parser.php(97): Symfony\Component\Yaml\Parser->doParse() #5 /var/www/html/vendor/symfony/yaml/Yaml.php(80): Symfony\Component\Yaml\Parser->parse() #6 /var/www/html/includes.php(466): Symfony\Component\Yaml\Yaml::parse() #7 /var/www/html/new.php(230): is_trusted_user() #8 {main} thrown in /var/www/html/vendor/symfony/yaml/Parser.php on line 350
```

**Comment by MatmaRex** [comment]
Looks like it's coming from the YAML parsing we do here: https://github.com/MatmaRex/patchdemo/blob/c852ece40d8043b853f2fab971fb26df72a9a26d/includes.php#L462-L466

I suppose somewhere in this file: https://raw.githubusercontent.com/wikimedia/integration-config/master/zuul/layout.yaml the `experimental` key is duplicated. This should probably be fixed in that repo.

YAML was a mistake…

**Comment by jdforrester** [comment]
Fixed with https://gerrit.wikimedia.org/r/c/integration/config/+/848505

**Comment by MatmaRex** [comment]
Oh, thanks!
